//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectdbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public Nullable<int> MaKH { get; set; }
        public Nullable<int> MaH { get; set; }
        public Nullable<int> ParentChatId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    }
}
