//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectdbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHDBan
    {
        public int MaHDBan { get; set; }
        public int MaH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual Hang Hang { get; set; }
        public virtual HDBan HDBan { get; set; }
    }
}
