//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectdbfirst.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBHmvcEntities : DbContext
    {
        public QLBHmvcEntities()
            : base("name=QLBHmvcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHDBan> CTHDBans { get; set; }
        public virtual DbSet<CTHDNhap> CTHDNhaps { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<Hang> Hangs { get; set; }
        public virtual DbSet<HDBan> HDBans { get; set; }
        public virtual DbSet<HDNhap> HDNhaps { get; set; }
        public virtual DbSet<KH> KHs { get; set; }
        public virtual DbSet<NCC> NCCs { get; set; }
        public virtual DbSet<NV> NVs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
